language: python
python:
  - "3.3"
  - "3.4"
  # PyPy versions
  - "pypy3" # Pypy3 2.4.0

# command to install dependencies
install:
  - pip install nltk
  - pip install mfnbc
# command to run tests
script: python test/test_mfnbc.py
